import json
import re

# We will define 20 high-quality questions for each of the 9 subjects, directly based on the Cesur official database topics.
questions = []

# 1. Aplicaciones Web (20)
web_qs = [
    {"question": "¿Qué herramienta externa online se utiliza habitualmente para escanear y auditar configuraciones SSL/TLS en un servidor web?", "options": ["SSL Labs (Qualys)", "Wireshark", "Nmap", "Pingdom"], "answer": "SSL Labs (Qualys)", "subject": "Aplicaciones Web"},
    {"question": "¿Qué archivo de configuración en servidores Apache permite configurar reglas de redirección y seguridad a nivel de directorio?", "options": [".htaccess", "web.config", "nginx.conf", "httpd.conf"], "answer": ".htaccess", "subject": "Aplicaciones Web"},
    {"question": "¿Qué panel de control web gratuito e in-situ permite administrar backups automáticos y bases de datos en servidores VPS?", "options": ["cPanel", "Webmin / Virtualmin", "Plesk", "DirectAdmin"], "answer": "Webmin / Virtualmin", "subject": "Aplicaciones Web"},
    {"question": "En WordPress, ¿qué archivo contiene los datos de conexión a la base de datos y las claves únicas de salazón?", "options": ["wp-config.php", "index.php", "functions.php", ".htaccess"], "answer": "wp-config.php", "subject": "Aplicaciones Web"},
    {"question": "¿Qué protocolo seguro utiliza por defecto el puerto 443 para la transferencia de páginas web hipertexto?", "options": ["HTTPS", "HTTP", "SFTP", "FTPS"], "answer": "HTTPS", "subject": "Aplicaciones Web"},
    {"question": "¿Cuál es la función principal de los gestores de contenido (CMS) como Drupal o Joomla?", "options": ["Compilar código binario", "Crear y gestionar contenido web de forma dinámica sin programar todo desde cero", "Auditar puertos de red abiertos", "Configurar el cortafuegos del servidor"], "answer": "Crear y gestionar contenido web de forma dinámica sin programar todo desde cero", "subject": "Aplicaciones Web"},
    {"question": "En desarrollo web, ¿para qué sirve el archivo robots.txt?", "options": ["Para guardar contraseñas", "Para dar instrucciones a los rastreadores de los buscadores sobre qué páginas indexar", "Para acelerar la carga de imágenes", "Para bloquear ataques DDoS"], "answer": "Para dar instrucciones a los rastreadores de los buscadores sobre qué páginas indexar", "subject": "Aplicaciones Web"},
    {"question": "¿Qué método HTTP se utiliza habitualmente en formularios web cuando queremos actualizar o modificar un recurso existente en el servidor?", "options": ["PUT / POST", "GET", "DELETE", "HEAD"], "answer": "PUT / POST", "subject": "Aplicaciones Web"},
    {"question": "En CSS, ¿qué propiedad define el orden de apilamiento vertical de los elementos posicionados?", "options": ["z-index", "position", "float", "display"], "answer": "z-index", "subject": "Aplicaciones Web"},
    {"question": "¿Qué etiqueta de HTML5 se utiliza para reproducir archivos de sonido de forma nativa sin plugins?", "options": ["<audio>", "<sound>", "<music>", "<embed>"], "answer": "<audio>", "subject": "Aplicaciones Web"},
    {"question": "¿Qué herramienta integrada en los navegadores web permite depurar errores de JavaScript y analizar la red?", "options": ["Herramientas de Desarrollador (F12)", "Administrador de Tareas", "Consola del Sistema", "Visual Studio Code"], "answer": "Herramientas de Desarrollador (F12)", "subject": "Aplicaciones Web"},
    {"question": "En bases de datos web, ¿qué comando SQL elimina permanentemente una base de datos completa?", "options": ["DROP DATABASE", "DELETE DATABASE", "REMOVE DATABASE", "TRUNCATE DATABASE"], "answer": "DROP DATABASE", "subject": "Aplicaciones Web"},
    {"question": "En JavaScript, ¿cuál de los siguientes bucles se ejecuta al menos una vez antes de comprobar la condición?", "options": ["do...while", "for", "while", "foreach"], "answer": "do...while", "subject": "Aplicaciones Web"},
    {"question": "En WordPress, ¿qué son los 'Custom Post Types'?", "options": ["Tipos de letra personalizados", "Tipos de contenido personalizados creados a medida del proyecto", "Configuraciones de seguridad del hosting", "Formatos de base de datos relacional"], "answer": "Tipos de contenido personalizados creados a medida del proyecto", "subject": "Aplicaciones Web"},
    {"question": "¿Qué formato de compresión de imágenes web es recomendado por Google por ofrecer alta calidad y menor peso que PNG/JPEG?", "options": ["WebP", "GIF", "BMP", "TIFF"], "answer": "WebP", "subject": "Aplicaciones Web"},
    {"question": "¿Qué plugin de WordPress es el estándar de oro para transformar una instalación normal en una tienda online completa?", "options": ["WooCommerce", "Yoast SEO", "Elementor", "Jetpack"], "answer": "WooCommerce", "subject": "Aplicaciones Web"},
    {"question": "En JavaScript, ¿qué método convierte un objeto o array en una cadena de texto en formato JSON?", "options": ["JSON.stringify()", "JSON.parse()", "Object.toString()", "JSON.toText()"], "answer": "JSON.stringify()", "subject": "Aplicaciones Web"},
    {"question": "¿Cuál es la función principal de una red de entrega de contenido (CDN) en aplicaciones web?", "options": ["Cifrar la base de datos de usuarios", "Distribuir copias estáticas de la web en servidores globales para acelerar la carga", "Crear copias de seguridad incrementales", "Alojar el dominio principal de la empresa"], "answer": "Distribuir copias estáticas de la web en servidores globales para acelerar la carga", "subject": "Aplicaciones Web"},
    {"question": "En desarrollo frontend, ¿qué significa la sigla DOM?", "options": ["Domain Object Model", "Document Object Model", "Digital Operating Mode", "Data Output Manager"], "answer": "Document Object Model", "subject": "Aplicaciones Web"},
    {"question": "¿Qué archivo del servidor web Nginx define la configuración de los bloques de servidor (servidores virtuales)?", "options": ["nginx.conf o archivos en sites-available", "web.config", ".htaccess", "httpd.conf"], "answer": "nginx.conf o archivos en sites-available", "subject": "Aplicaciones Web"}
]
questions.extend(web_qs)

# 2. Digitalización & IA (20)
digi_qs = [
    {"question": "¿Qué modelo de servicio en la nube ofrece un entorno de desarrollo completo (como Heroku o Google App Engine) sin administrar servidores?", "options": ["PaaS", "IaaS", "SaaS", "BaaS"], "answer": "PaaS", "subject": "Digitalización"},
    {"question": "¿Qué concepto de la Industria 4.0 describe la simulación virtual de un proceso o producto físico alimentado con datos en tiempo real?", "options": ["Gemelo Digital (Digital Twin)", "Realidad Virtual", "Big Data", "Cloud Privado"], "answer": "Gemelo Digital (Digital Twin)", "subject": "Digitalización"},
    {"question": "¿Cuál de las llamadas 3 V's del Big Data se refiere a la rapidez con la que se reciben y procesan los flujos masivos de información?", "options": ["Velocidad", "Volumen", "Variedad", "Veracidad"], "answer": "Velocidad", "subject": "Digitalización"},
    {"question": "En Cloud Computing, ¿qué característica permite aumentar o disminuir los recursos de forma automática según la demanda?", "options": ["Escalabilidad y Elasticidad", "Redundancia", "Interoperabilidad", "Latencia física"], "answer": "Escalabilidad y Elasticidad", "subject": "Digitalización"},
    {"question": "¿Qué tipo de nube es de uso exclusivo para una sola organización y ofrece el máximo control y seguridad sobre los datos?", "options": ["Nube Privada", "Nube Pública", "Nube Híbrida", "Nube Comunitaria"], "answer": "Nube Privada", "subject": "Digitalización"},
    {"question": "¿Qué es la Inteligencia Artificial Generativa (IA Generativa)?", "options": ["Sistemas de IA entrenados para crear contenido nuevo y original (como textos, imágenes o código)", "Algoritmos que solo clasifican correos como spam", "Robots que limpian almacenes de forma física", "Sistemas de cálculo matemático tradicional"], "answer": "Sistemas de IA entrenados para crear contenido nuevo y original (como textos, imágenes o código)", "subject": "Digitalización"},
    {"question": "En Inteligencia Artificial, ¿qué significan las siglas LLM?", "options": ["Language Learning Method", "Large Language Model (Gran Modelo de Lenguaje)", "Linear Logic Machine", "Linked Learning Memory"], "answer": "Large Language Model (Gran Modelo de Lenguaje)", "subject": "Digitalización"},
    {"question": "¿Qué es el Deep Learning o Aprendizaje Profundo?", "options": ["Un subcampo del Machine Learning basado en redes neuronales artificiales multicapa", "Un tipo de almacenamiento físico en servidores submarinos", "La programación lineal estructurada con C++", "La optimización de consultas SQL en Big Data"], "answer": "Un subcampo del Machine Learning basado en redes neuronales artificiales multicapa", "subject": "Digitalización"},
    {"question": "En el uso de modelos de IA de lenguaje, ¿qué es la ingeniería de prompts (Prompt Engineering)?", "options": ["Diseñar el microprocesador de los servidores de IA", "El arte de redactar instrucciones precisas para obtener el mejor resultado de la IA", "Programar la interfaz de usuario de ChatGPT", "Limpiar la base de datos de entrenamiento"], "answer": "El arte de redactar instrucciones precisas para obtener el mejor resultado de la IA", "subject": "Digitalización"},
    {"question": "En Inteligencia Artificial, ¿qué es una alucinación?", "options": ["Un fallo del disco duro del servidor", "Cuando la IA genera respuestas falsas o inventadas con total apariencia de seguridad", "El calentamiento de las tarjetas gráficas (GPUs)", "Un virus informático avanzado"], "answer": "Cuando la IA genera respuestas falsas o inventadas con total apariencia de seguridad", "subject": "Digitalización"},
    {"question": "¿Qué ley europea regula el desarrollo y comercialización ética y segura de los sistemas de IA?", "options": ["El RGPD", "La AI Act (Reglamento de Inteligencia Artificial de la UE)", "La Directiva NIS 2", "La ley de propiedad intelectual"], "answer": "La AI Act (Reglamento de Inteligencia Artificial de la UE)", "subject": "Digitalización"},
    {"question": "¿Qué es el Procesamiento del Lenguaje Natural (NLP)?", "options": ["Un protocolo de comunicación entre routers Cisco", "La rama de la IA encargada de que las máquinas entiendan, interpreten y manipulen el lenguaje humano", "Un tipo de programación estructurada en pseudocódigo", "La traducción automática de direcciones IPv4 a nombres"], "answer": "La rama de la IA encargada de que las máquinas entiendan, interpreten y manipulen el lenguaje humano", "subject": "Digitalización"},
    {"question": "¿Qué tipo de aprendizaje automático utiliza etiquetas de datos (respuestas correctas) para entrenar al modelo?", "options": ["Aprendizaje Supervisado", "Aprendizaje No Supervisado", "Aprendizaje por Refuerzo", "Deep Clustering"], "answer": "Aprendizaje Supervisado", "subject": "Digitalización"},
    {"question": "En Inteligencia Artificial, ¿qué es la visión artificial (Computer Vision)?", "options": ["La capacidad de las máquinas para procesar y comprender imágenes y vídeos digitales", "Un software para ajustar el brillo de los monitores", "El diseño físico de los centros de datos", "Un método para analizar el código fuente mediante colores"], "answer": "La capacidad de las máquinas para procesar y comprender imágenes y vídeos digitales", "subject": "Digitalización"},
    {"question": "¿Cuál de los siguientes es un ejemplo de Software como Servicio (SaaS)?", "options": ["Un servidor dedicado físico", "Microsoft Office 365 / Google Workspace", "Un VPS con Ubuntu Server instalado", "Un router configurado con VLANs"], "answer": "Microsoft Office 365 / Google Workspace", "subject": "Digitalización"},
    {"question": "¿Qué significa el concepto de 'Edge Computing'?", "options": ["Enviar todos los datos a la nube centralizada", "Procesar los datos cerca del lugar donde se generan para reducir la latencia", "Hacer copias de seguridad de datos en discos externos", "Virtualizar redes locales"], "answer": "Procesar los datos cerca del lugar donde se generan para reducir la latencia", "subject": "Digitalización"},
    {"question": "En Big Data, ¿qué diferencia los datos estructurados de los no estructurados?", "options": ["Los estructurados tienen un formato rígido y definido (tablas SQL), mientras que los no estructurados carecen de formato fijo (vídeos, PDFs, audios)", "Los estructurados se guardan en la nube y los no estructurados en local", "Los estructurados son seguros y los no estructurados contienen malware", "No hay diferencia real"], "answer": "Los activos físicos, intelectuales, humanos o financieros imprescindibles para que el modelo de negocio funcione", "answer": "Los estructurados tienen un formato rígido y definido (tablas SQL), mientras que los no estructurados carecen de formato fijo (vídeos, PDFs, audios)", "subject": "Digitalización"},
    {"question": "En IA, ¿qué es el sesgo algorítmico (Bias)?", "options": ["El consumo eléctrico de los modelos", "Prejuicios o desviaciones sistemáticas en las respuestas de la IA debido a datos de entrenamiento no representativos o mal diseñados", "La velocidad de inferencia de la GPU", "La pérdida de memoria en redes neuronales"], "answer": "Prejuicios o desviaciones sistemáticas en las respuestas de la IA debido a datos de entrenamiento no representativos o mal diseñados", "subject": "Digitalización"},
    {"question": "¿Qué tecnología descentralizada permite certificar la autenticidad de transacciones mediante bloques cifrados y enlazados?", "options": ["Blockchain", "Active Directory", "Virtualización KVM", "Prometheus"], "answer": "Blockchain", "subject": "Digitalización"},
    {"question": "En el entrenamiento de modelos de IA, ¿qué es el Overfitting o sobreajuste?", "options": ["El sobrecalentamiento del procesador del servidor", "Cuando el modelo memoriza los datos de entrenamiento y falla al intentar generalizar con datos nuevos", "El proceso de empaquetar el software en Docker", "La optimización del peso de los archivos JSON"], "answer": "Cuando el modelo memoriza los datos de entrenamiento y falla al intentar generalizar con datos nuevos", "subject": "Digitalización"}
]
questions.extend(digi_qs)

# 3. Sistemas Operativos en Red (20)
sor_qs = [
    {"question": "¿Qué consola de Windows Server se utiliza habitualmente para configurar y administrar las relaciones de confianza entre dominios?", "options": ["Dominios y confianzas de Active Directory", "Usuarios y equipos de Active Directory", "Administrador del Servidor", "PowerShell de Windows"], "answer": "Dominios y confianzas de Active Directory", "subject": "Sistemas Operativos en red"},
    {"question": "¿En qué se basa tradicionalmente la jerarquía de nombres de un dominio en una red con Active Directory?", "options": ["En el sistema de nombres DNS", "En las direcciones IP estáticas", "En los nombres NetBIOS locales", "En las direcciones MAC de los equipos"], "answer": "En el sistema de nombres DNS", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué asistente o herramienta se inicia en Windows Server para finalizar la configuración de un servidor como Controlador de Dominio tras instalar el rol de AD DS?", "options": ["Promover este servidor a controlador de dominio", "Asistente de configuración de DHCP", "Consola dcpromo (en versiones antiguas)", "Administrador de políticas de grupo"], "answer": "Promover este servidor a controlador de dominio", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué comando de Linux permite cambiar el propietario y el grupo de un archivo de forma simultánea?", "options": ["chown propietario:grupo archivo", "chmod 777 archivo", "chgrp grupo archivo", "passwd usuario"], "answer": "chown propietario:grupo archivo", "subject": "Sistemas Operativos en red"},
    {"question": "En Windows Server, ¿qué objeto de Active Directory sirve exclusivamente como contenedor lógico para organizar usuarios, equipos y aplicar GPOs?", "options": ["Unidad Organizativa (OU)", "Grupo de Seguridad", "Grupo de Distribución", "Dominio Principal"], "answer": "Unidad Organizativa (OU)", "subject": "Sistemas Operativos en red"},
    {"question": "¿Cuál es la función del comando 'systemctl restart service' en sistemas operativos Linux?", "options": ["Borrar los registros de configuración del servicio", "Detener e iniciar inmediatamente un servicio o demonio del sistema", "Crear una tarea programada para el servicio", "Habilitar el servicio para que arranque al encender el sistema"], "answer": "Detener e iniciar inmediatamente un servicio o demonio del sistema", "subject": "Sistemas Operativos en red"},
    {"question": "En Windows Server, ¿cuál de los siguientes grupos tiene permisos totales para administrar todo el bosque de dominios?", "options": ["Administradores del bosque (Enterprise Admins)", "Administradores del Dominio", "Operadores de copia", "Usuarios del Dominio"], "answer": "Administradores del bosque (Enterprise Admins)", "subject": "Sistemas Operativos en red"},
    {"question": "¿En qué archivo de configuración de Linux se definen los sistemas de archivos que se montarán automáticamente al iniciar el equipo?", "options": ["/etc/fstab", "/etc/mtab", "/etc/exports", "/etc/resolv.conf"], "answer": "/etc/fstab", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué servicio de Windows Server permite sincronizar los directorios activos locales con la nube de Azure (Entra ID)?", "options": ["Microsoft Entra Connect (Azure AD Connect)", "DFS Replication", "DirectAccess", "IIS Server"], "answer": "Microsoft Entra Connect (Azure AD Connect)", "subject": "Sistemas Operativos en red"},
    {"question": "En Linux, ¿qué comando muestra los sistemas de archivos montados y su espacio libre en formato legible humano?", "options": ["df -h", "du -sh", "lsblk", "fdisk -l"], "answer": "df -h", "subject": "Sistemas Operativos en red"},
    {"question": "En Active Directory, ¿qué diferencia principal hay entre un Grupo de Seguridad y un Grupo de Distribución?", "options": ["Los de seguridad se usan para asignar permisos de acceso, mientras que los de distribución se usan solo para listas de correo", "Los de seguridad solo contienen usuarios y los de distribución contienen equipos", "No hay ninguna diferencia técnica", "Los de seguridad requieren licencia Enterprise"], "answer": "Los de seguridad se usan para asignar permisos de acceso, mientras que los de distribución se usan solo para listas de correo", "subject": "Sistemas Operativos en red"},
    {"question": "¿Cuál de los siguientes comandos de Linux se utiliza para ver las últimas líneas de un archivo de registro (log) de forma dinámica?", "options": ["tail -f", "head -n", "cat", "less"], "answer": "tail -f", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué comando de PowerShell permite forzar la actualización inmediata de las Directivas de Grupo (GPOs) en un cliente Windows?",
     "options": ["gpupdate /force", "Update-GPO", "gpfixup", "Set-GPInheritance"], "answer": "gpupdate /force", "subject": "Sistemas Operativos en red"},
    {"question": "En Linux, ¿qué permisos octales corresponden a la configuración de lectura, escritura y ejecución para el propietario, y lectura y ejecución para el resto?", "options": ["755", "644", "777", "700"], "answer": "755", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué protocolo utiliza Windows Server de forma nativa para proporcionar resolución de nombres NetBIOS en redes antiguas?", "options": ["WINS", "DNS", "LLMNR", "LDAP"], "answer": "WINS", "subject": "Sistemas Operativos en red"},
    {"question": "En Active Directory, ¿qué es la 'herencia' de directivas de grupo?", "options": ["El traspaso de permisos de una cuenta a otra al jubilarse el trabajador", "Que las GPOs aplicadas a una Unidad Organizativa padre se aplican automáticamente a sus OUs e hijos inferiores", "La copia de seguridad automática del dominio", "La migración de datos hacia Azure"], "answer": "Que las GPOs aplicadas a una Unidad Organizativa padre se aplican automáticamente a sus OUs e hijos inferiores", "subject": "Sistemas Operativos en red"},
    {"question": "En sistemas Linux, ¿qué comando cambia la contraseña del usuario actual?", "options": ["passwd", "password", "changepass", "shadow"], "answer": "passwd", "subject": "Sistemas Operativos en red"},
    {"question": "En Windows Server, ¿qué rol se encarga de almacenar y replicar archivos entre diferentes servidores de forma centralizada ofreciendo una única ruta?", "options": ["DFS (Sistemas de Archivos Distribuido)", "Storage Replica", "WDS", "File Server Resource Manager"], "answer": "DFS (Sistemas de Archivos Distribuido)", "subject": "Sistemas Operativos en red"},
    {"question": "¿Qué comando de Linux muestra los permisos, propietario, tamaño y fecha de modificación de los archivos de un directorio detalladamente?", "options": ["ls -l", "ls -a", "dir", "show files"], "answer": "ls -l", "subject": "Sistemas Operativos en red"},
    {"question": "En Active Directory, ¿qué significa que una GPO tenga activada la opción 'Exigida' (Enforced)?", "options": ["Que los usuarios no pueden apagar el equipo", "Que la directiva se aplicará obligatoriamente sobreescribiendo cualquier bloqueo de herencia de OUs inferiores", "Que requiere autenticación de dos factores", "Que expira en 24 horas"], "answer": "Que la directiva se aplicará obligatoriamente sobreescribiendo cualquier bloqueo de herencia de OUs inferiores", "subject": "Sistemas Operativos en red"}
]
questions.extend(sor_qs)

# 4. Servicios Red (20)
red_qs = [
    {"question": "En la instalación web del cliente de correo Roundcube, ¿por qué es crítico eliminar la carpeta del instalador tras finalizar?", "options": ["Para liberar espacio en el disco duro", "Por seguridad, para evitar que terceros puedan reconfigurar la base de datos o acceder al sistema", "Porque si no se borra, el servicio SMTP se bloquea", "No es necesario borrarla"], "answer": "Por seguridad, para evitar que terceros puedan reconfigurar la base de datos o acceder al sistema", "subject": "Servicios Red"},
    {"question": "¿Para qué se utiliza habitualmente la codificación 'quoted-printable' en las cabeceras e hilos de correo con formato MIME?", "options": ["Para cifrar el cuerpo del correo de extremo a extremo", "Para representar caracteres especiales o no ASCII de forma segura usando texto imprimible estándar de 7 bits", "Para comprimir archivos adjuntos pesados", "Para ocultar la dirección IP del remitente"], "answer": "Para representar caracteres especiales o no ASCII de forma segura usando texto imprimible estándar de 7 bits", "subject": "Servicios Red"},
    {"question": "¿Qué puerto se recomienda estándar para establecer una conexión segura SMTP cifrada mediante el uso de STARTTLS?", "options": ["587", "465", "25", "993"], "answer": "587", "subject": "Servicios Red"},
    {"question": "En el protocolo DNS, ¿qué tipo de registro permite definir la dirección IP del servidor DNS de autoridad para el dominio?", "options": ["NS", "MX", "A", "CNAME"], "answer": "NS", "subject": "Servicios Red"},
    {"question": "¿Qué protocolo seguro se utiliza comúnmente para transferir páginas web cifrando todo el tráfico con TLS/SSL?", "options": ["HTTPS", "HTTP", "SFTP", "FTPS"], "answer": "HTTPS", "subject": "Servicios Red"},
    {"question": "En un servidor DHCP corporativo, ¿qué es la reserva de direcciones IP?", "options": ["Un rango de IPs que no se pueden asignar bajo ningún concepto", "Asociar de forma fija una IP específica a la dirección MAC de un cliente para que siempre obtenga la misma dirección", "El tiempo que dura activa la concesión de red", "La velocidad máxima reservada al administrador"], "answer": "Asociar de forma fija una IP específica a la dirección MAC de un cliente para que siempre obtenga la misma dirección", "subject": "Servicios Red"},
    {"question": "¿Qué servicio DNS amplía el protocolo básico añadiendo firmas criptográficas para evitar la suplantación de identidad en las respuestas?", "options": ["DNSSEC", "DNScrypt", "DNS sobre HTTPS", "DHCP Snooping"], "answer": "DNSSEC", "subject": "Servicios Red"},
    {"question": "¿Qué puerto TCP/UDP por defecto utiliza el protocolo NTP para la sincronización de la fecha y hora en red?", "options": ["123", "53", "161", "143"], "answer": "123", "subject": "Servicios Red"},
    {"question": "En el servidor de correo postfix, ¿cuál es el archivo de configuración principal donde se establecen los dominios locales y el enrutamiento?", "options": ["main.cf", "master.cf", "postfix.conf", "sendmail.cf"], "answer": "main.cf", "subject": "Servicios Red"},
    {"question": "¿Qué protocolo y puerto utiliza por defecto el servicio IMAP con cifrado SSL/TLS seguro para recibir correos del servidor?", "options": ["IMAPS (Puerto 993)", "POP3S (Puerto 995)", "SMTPS (Puerto 465)", "HTTPS (Puerto 443)"], "answer": "IMAPS (Puerto 993)", "subject": "Servicios Red"},
    {"question": "En una zona DNS inversa, ¿qué tipo de registro asocia una dirección IP con su nombre de dominio correspondiente?", "options": ["PTR", "A", "CNAME", "MX"], "answer": "PTR", "subject": "Servicios Red"},
    {"question": "¿Qué directiva del servidor DHCP define la dirección IP del router o puerta de enlace predeterminada que se entregará a los clientes?", "options": ["routers / option routers", "domain-name-servers", "subnet-mask", "default-lease-time"], "answer": "routers / option routers", "subject": "Servicios Red"},
    {"question": "¿Cuál es la función principal del archivo de configuración /etc/bind/named.conf.local en un servidor DNS BIND9?", "options": ["Declarar las zonas DNS locales (directas e inversas) que administrará el servidor", "Configurar los redireccionadores DNS globales", "Definir los permisos de lectura de la carpeta", "Asignar las IPs estáticas del servidor"], "answer": "Declarar las zonas DNS locales (directas e inversas) que administrará el servidor", "subject": "Servicios Red"},
    {"question": "¿Qué comando de consola en Linux permite realizar consultas DNS detalladas a servidores específicos, similar a nslookup?", "options": ["dig", "ping", "netstat", "ip addr"], "answer": "dig", "subject": "Servicios Red"},
    {"question": "En redes, ¿qué protocolo traduce direcciones MAC de capa 2 en direcciones IP de capa 3 o viceversa en IPv4?", "options": ["ARP", "DHCP", "ICMP", "DNS"], "answer": "ARP", "subject": "Servicios Red"},
    {"question": "En un servidor web Apache, ¿qué directiva dentro del archivo de configuración define el puerto de escucha del servidor?", "options": ["Listen", "Port", "ServerName", "VirtualHost"], "answer": "Listen", "subject": "Servicios Red"},
    {"question": "¿Qué protocolo ligero de directorio se utiliza para la centralización y autenticación de usuarios de red compatibles con Linux?", "options": ["LDAP", "Active Directory", "Samba", "Kerberos"], "answer": "LDAP", "subject": "Servicios Red"},
    {"question": "En DHCP, ¿qué mensaje envía el servidor DHCP al cliente para confirmar formalmente la asignación de la dirección IP?", "options": ["DHCPACK", "DHCPOFFER", "DHCPREQUEST", "DHCPDISCOVER"], "answer": "DHCPACK", "subject": "Servicios Red"},
    {"question": "¿Qué archivo local mapea los puertos bien conocidos con los nombres de servicios correspondientes en sistemas Unix/Linux?", "options": ["/etc/services", "/etc/protocols", "/etc/hosts", "/etc/resolv.conf"], "answer": "/etc/services", "subject": "Servicios Red"},
    {"question": "En Apache o Nginx, ¿qué es un Host Virtual (VirtualHost / Server Block)?", "options": ["Una máquina virtual completa con sistema operativo", "Una configuración que permite alojar y servir múltiples sitios web con dominios diferentes en el mismo servidor físico e IP", "Una copia de seguridad del servidor", "Un panel de administración en la nube"], "answer": "Una configuración que permite alojar y servir múltiples sitios web con dominios diferentes en el mismo servidor físico e IP", "subject": "Servicios Red"}
]
questions.extend(red_qs)

# 5. Seguridad Informática (20)
seg_qs = [
    {"question": "¿Qué ley española regula el comercio electrónico y los servicios prestados a través de Internet (como tiendas online o webs corporativas)?", "options": ["LSSI-CE (Ley de Servicios de la Sociedad de la Información)", "LOPDGDD", "Estatuto de los Trabajadores", "Ley de Propiedad Intelectual"], "answer": "LSSI-CE (Ley de Servicios de la Sociedad de la Información)", "subject": "Seguridad Informatica"},
    {"question": "En un servidor NAS empresarial, ¿para qué sirve configurar un sistema DFS (Distributed File System)?", "options": ["Para encriptar los discos", "Para unificar carpetas compartidas ubicadas en diferentes servidores en un único espacio de nombres lógico", "Para distribuir la carga eléctrica", "Para analizar malware automáticamente"], "answer": "Para unificar carpetas compartidas ubicadas en diferentes servidores en un único espacio de nombres lógico", "subject": "Seguridad Informatica"},
    {"question": "Los sistemas NAS de gama media/alta permiten conectar cabinas de almacenamiento externo adicionales mediante puertos específicos como:", "options": ["eSATA o puertos SAS de expansión", "Puertos Jack de audio", "Puertos VGA", "Puertos de consola serie"], "answer": "eSATA o puertos SAS de expansión", "subject": "Seguridad Informatica"},
    {"question": "¿Qué principio de seguridad busca garantizar que la información solo esté accesible para aquellos usuarios autorizados?", "options": ["Confidencialidad", "Integridad", "Disponibilidad", "No repudio"], "answer": "Confidencialidad", "subject": "Seguridad Informatica"},
    {"question": "¿Qué método criptográfico utiliza dos claves diferentes pero matemáticamente relacionadas (una pública y una privada)?", "options": ["Cifrado Asimétrico", "Cifrado Simétrico", "Cifrado César", "Algoritmo hash MD5"], "answer": "Cifrado Asimétrico", "subject": "Seguridad Informatica"},
    {"question": "¿Qué protocolo de encriptación de red se utiliza para crear conexiones seguras VPN a nivel de capa de red IP?", "options": ["IPsec", "HTTPS", "SSH", "WPA2"], "answer": "IPsec", "subject": "Seguridad Informatica"},
    {"question": "En auditoría de seguridad, ¿qué es un test de penetración (Pentesting)?", "options": ["Un ataque cibernético real no autorizado para robar fondos", "Un ataque simulado y autorizado para evaluar la seguridad de los sistemas detectando fallos antes que los hackers", "La instalación de software antivirus corporativo", "Un examen teórico de seguridad a la plantilla"], "answer": "Un ataque simulado y autorizado para evaluar la seguridad de los sistemas detectando fallos antes que los hackers", "subject": "Seguridad Informatica"},
    {"question": "¿Cuál es la función del protocolo HTTPS respecto al protocolo HTTP básico?", "options": ["Acelerar la carga de la página", "Cifrar el tráfico de datos entre el navegador del cliente y el servidor mediante SSL/TLS", "Bloquear anuncios molestos", "Evitar ataques de fuerza bruta al dominio"], "answer": "Cifrar el tráfico de datos entre el navegador del cliente y el servidor mediante SSL/TLS", "subject": "Seguridad Informatica"},
    {"question": "¿Qué ley regula la protección de datos personales y garantía de derechos digitales en España adaptada al reglamento europeo?", "options": ["LOPDGDD (Ley Orgánica 3/2018)", "LSSI", "Constitución Española", "Ley General de Telecomunicaciones"], "answer": "LOPDGDD (Ley Orgánica 3/2018)", "subject": "Seguridad Informatica"},
    {"question": "En almacenamiento de datos, ¿qué configuración RAID distribuye los datos a nivel de bloques duplicándolos exactamente en un segundo disco espejo?", "options": ["RAID 1", "RAID 0", "RAID 5", "RAID 10"], "answer": "RAID 1", "subject": "Seguridad Informatica"},
    {"question": "En seguridad perimetral, ¿qué hace un firewall de filtrado de paquetes simple?", "options": ["Analiza el contenido detallado de los correos", "Examina las cabeceras de los paquetes comparando puertos, IPs y protocolos contra reglas definidas", "Cifra los discos del servidor local", "Bloquea el acceso físico a la sala de servidores"], "answer": "Examina las cabeceras de los paquetes comparando puertos, IPs y protocolos contra reglas definidas", "subject": "Seguridad Informatica"},
    {"question": "¿Qué amenaza describe al malware que recopila información sobre el uso del equipo y los hábitos de navegación del usuario sin su permiso?", "options": ["Spyware", "Ransomware", "Virus", "Rootkit"], "answer": "Spyware", "subject": "Seguridad Informatica"},
    {"question": "¿Qué ataque busca sobrecargar un servidor web enviándole tráfico desde miles de IPs diferentes al mismo tiempo?", "options": ["Ataque DDoS (Denegación de Servicio Distribuida)", "Inyección SQL", "Fuerza Bruta", "Phishing"], "answer": "Ataque DDoS (Denegación de Servicio Distribuida)", "subject": "Seguridad Informatica"},
    {"question": "¿Cuál es el objetivo principal del análisis de riesgos en una organización?", "options": ["Comprar el hardware más caro", "Identificar los activos de información, las amenazas a las que están expuestos y calcular el impacto potencial para aplicar medidas correctoras", "Despedir a los empleados que cometan errores informáticos", "Instalar el sistema operativo Linux en todos los terminales"], "answer": "Identificar los activos de información, las amenazas a las que están expuestos y calcular el impacto potencial para aplicar medidas correctoras", "subject": "Seguridad Informatica"},
    {"question": "En criptografía, ¿qué es un algoritmo hash (como SHA-256)?", "options": ["Un cifrado de datos reversible de alta velocidad", "Una función matemática unidireccional que genera una firma de longitud fija a partir de un archivo para verificar su integridad", "Un protocolo seguro de enrutamiento", "Un sistema de copias de seguridad incrementales"], "answer": "Una función matemática unidireccional que genera una firma de longitud fija a partir de un archivo para verificar su integridad", "subject": "Seguridad Informatica"},
    {"question": "¿Qué significan las siglas DLP en seguridad informática?", "options": ["Direct Loop Protocol", "Prevención de Pérdida de Datos (Data Loss Prevention)", "Dynamic Link Port", "Decryption Local Path"], "answer": "Prevención de Pérdida de Datos (Data Loss Prevention)", "subject": "Seguridad Informatica"},
    {"question": "¿Qué tipo de copia de seguridad realiza una copia de todos los datos modificados desde la última copia completa?", "options": ["Copia Diferencial", "Copia Incremental", "Copia Completa", "Copia en Espejo"], "answer": "Copia Diferencial", "subject": "Seguridad Informatica"},
    {"question": "¿Qué protocolo seguro sustituyó al antiguo protocolo SSL por presentar este graves vulnerabilidades de seguridad?", "options": ["TLS", "HTTPS", "SSH", "VPN"], "answer": "TLS", "subject": "Seguridad Informatica"},
    {"question": "En el contexto de la ciberseguridad, ¿qué es el 'Zero Trust' o confianza cero?", "options": ["Un antivirus que no confía en ninguna firma", "Un modelo de seguridad que asume que las amenazas están en todas partes y requiere autenticar rigurosamente cada petición de acceso", "Un cortafuegos desactivado", "El nivel de seguridad de las redes públicas wifi"], "answer": "Un modelo de seguridad que asume que las amenazas están en todas partes y requiere autenticar rigurosamente cada petición de acceso", "subject": "Seguridad Informatica"},
    {"question": "¿Qué es la autenticación multifactor (MFA)?", "options": ["Introducir la misma contraseña varias veces consecutivas", "Un método de acceso que requiere dos o más pruebas independientes para verificar la identidad (contraseña + código móvil, etc.)", "Compartir los permisos de administrador entre varios usuarios", "Tener varios perfiles de usuario locales creados"], "answer": "Un método de acceso que requiere dos o más pruebas independientes para verificar la identidad (contraseña + código móvil, etc.)", "subject": "Seguridad Informatica"}
]
questions.extend(seg_qs)

# 6. HLC (20)
hlc_qs = [
    {"question": "Según el vocabulario internacional de tecnología definido en la norma ISO/IEC 2382, ¿cómo se define la interoperabilidad?", "options": ["La capacidad de dos o más sistemas informáticos para intercambiar información y utilizar de forma efectiva la información intercambiada", "El proceso de encriptación de bases de datos", "La velocidad máxima de transmisión física de los cables", "La virtualización de contenedores ligeros"], "answer": "La capacidad de dos o más sistemas informáticos para intercambiar información y utilizar de forma efectiva la información intercambiada", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "¿Por qué en el modelo de nube privada es necesaria una cualificación técnica muy específica del equipo de sistemas?", "options": ["Porque el equipo de la empresa debe encargarse por sí mismo de diseñar, desplegar y mantener toda la infraestructura física y lógica del cloud sin soporte del proveedor", "Porque las nubes públicas están prohibidas para almacenar datos sensibles", "Porque los servidores virtuales no se pueden configurar con interfaces gráficas", "No es necesaria ninguna cualificación especial"], "answer": "Porque el equipo de la empresa debe encargarse por sí mismo de diseñar, desplegar y mantener toda la infraestructura física y lógica del cloud sin soporte del proveedor", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "¿Qué es el cloud computing según el estándar del NIST?", "options": ["Un modelo que permite el acceso bajo demanda en red a un conjunto compartido de recursos de cómputo configurables de forma rápida y con mínimo esfuerzo", "Un conjunto de ordenadores de sobremesa en una oficina", "Un programa informático para gestionar redes cableadas", "El almacenamiento de archivos en discos duros locales"], "answer": "Un modelo que permite el acceso bajo demanda en red a un conjunto compartido de recursos de cómputo configurables de forma rápida y con mínimo esfuerzo", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En virtualización, ¿qué es un hipervisor tipo 1 (Bare Metal)?", "options": ["Un sistema operativo virtual dentro de Windows", "Un hipervisor que se ejecuta directamente sobre el hardware físico de la máquina sin sistema operativo anfitrión previo", "Un software similar a VirtualBox", "Una partición lógica cifrada"], "answer": "Un hipervisor que se ejecuta directamente sobre el hardware físico de la máquina sin sistema operativo anfitrión previo", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "¿Qué herramienta de automatización basada en contenedores ligeros permite ejecutar y empaquetar una aplicación con todas sus dependencias?", "options": ["Docker", "Kubernetes", "VirtualBox", "Ansible"], "answer": "Docker", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En automatización de infraestructura, ¿qué formato estructurado de datos utiliza Ansible en sus Playbooks?", "options": ["YAML", "JSON", "XML", "CSV"], "answer": "YAML", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En un script de Bash, ¿cómo se definen los parámetros o argumentos recibidos por la línea de comandos dentro del script?", "options": ["Mediante las variables especiales $1, $2, $3, etc.", "Mediante las variables %1, %2, %3", "Con var1, var2, var3", "Mediante la función read()"], "answer": "Mediante las variables especiales $1, $2, $3, etc.", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En virtualización con Docker, ¿cuál es la diferencia principal entre una Imagen y un Contenedor?", "options": ["La imagen es una plantilla inmutable de solo lectura, mientras que el contenedor es la instancia ejecutable y viva de esa imagen", "La imagen se guarda en local y el contenedor en la nube", "No hay diferencias técnicas", "La imagen es un archivo comprimido .zip"], "answer": "La imagen es una plantilla inmutable de solo lectura, mientras que el contenedor es la instancia ejecutable y viva de esa imagen", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En monitorización de servidores y redes, ¿cuál es la función de Prometheus?", "options": ["Un servidor web Apache", "Un sistema de monitorización de código abierto que recopila y almacena métricas en forma de series temporales", "Un cortafuegos perimetral", "Un motor de bases de datos relacionales SQL"], "answer": "Un sistema de monitorización de código abierto que recopila y almacena métricas en forma de series temporales", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En bases de datos NoSQL, ¿qué tipo de modelo de almacenamiento utiliza MongoDB?", "options": ["Modelo Documental (almacena documentos tipo BSON/JSON)", "Modelo Relacional (tablas y columnas)", "Modelo de Grafo", "Modelo Clave-Valor plano"], "answer": "Modelo Documental (almacena documentos tipo BSON/JSON)", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En scripting de Bash, ¿para qué sirve la primera línea que contiene '#!/bin/bash' (Shebang)?", "options": ["Para comentar el script y que no se ejecute", "Para indicar al sistema operativo el intérprete de comandos que debe usar para ejecutar el script", "Para dar permisos de ejecución automáticamente", "Es opcional y no tiene ninguna función"], "answer": "Para indicar al sistema operativo el intérprete de comandos que debe usar para ejecutar el script", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En Git, ¿qué comando añade todos los archivos modificados del directorio de trabajo al área de preparación (staging area)?", "options": ["git add .", "git commit -a", "git push", "git save"], "answer": "git add .", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En Python, ¿cuál de los siguientes tipos de datos representa una lista inmutable de elementos ordenados?", "options": ["Tupla (tuple)", "Lista (list)", "Diccionario (dict)", "Conjunto (set)"], "answer": "Tupla (tuple)", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "¿Qué comando de Linux permite programar la ejecución periódica de scripts y tareas del usuario de forma automática?", "options": ["crontab -e", "cron -add", "schedule", "systemctl start cron"], "answer": "crontab -e", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En redes, ¿qué protocolo se utiliza habitualmente para monitorizar de forma remota y recibir alertas de dispositivos como switches o routers?", "options": ["SNMP", "SMTP", "SSH", "NTP"], "answer": "SNMP", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En Docker, ¿para qué sirve el comando 'docker compose up'?", "options": ["Para apagar todos los contenedores activos", "Para compilar y arrancar de forma conjunta múltiples contenedores definidos en un archivo docker-compose.yml", "Para descargar una sola imagen del repositorio", "Para ver el log de un contenedor"], "answer": "Para compilar y arrancar de forma conjunta múltiples contenedores definidos en un archivo docker-compose.yml", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En la gestión de servidores Linux, ¿para qué sirve el archivo de configuración /etc/sudoers?", "options": ["Para guardar las contraseñas de los usuarios del sistema", "Para definir las reglas de privilegios del comando sudo (qué usuarios pueden ejecutar comandos como root)", "Para configurar las interfaces de red locales", "Para montar particiones de disco"], "answer": "Para definir las reglas de privilegios del comando sudo (qué usuarios pueden ejecutar comandos como root)", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En virtualización, ¿qué es un contenedor de tipo LXC (Linux Containers)?", "options": ["Un hipervisor tipo Bare Metal", "Una virtualización a nivel de sistema operativo para ejecutar múltiples entornos Linux aislados compartiendo el mismo kernel", "Una partición lógica NTFS", "Un disco duro físico SSD"], "answer": "Una virtualización a nivel de sistema operativo para ejecutar múltiples entornos Linux aislados compartiendo el mismo kernel", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En bases de datos relacionales, ¿qué restricción garantiza la integridad referencial conectando una tabla con otra?", "options": ["Clave Foránea (Foreign Key)", "Clave Primaria (Primary Key)", "Restricción Unique", "Check Constraint"], "answer": "Clave Foránea (Foreign Key)", "subject": "HLC (Horas de Libre Configuración)"},
    {"question": "En scripting de Bash, ¿cómo se verifica si un archivo existe y es un archivo regular en una estructura condicional 'if'?", "options": ["if [ -f archivo ]", "if [ -d archivo ]", "if [ -e archivo ]", "if [ -x archivo ]"], "answer": "if [ -f archivo ]", "subject": "HLC (Horas de Libre Configuración)"}
]
questions.extend(hlc_qs)

# 7. Inglés (20)
ing_qs = [
    {"question": "Particularly means:", "options": ["Especialmente / en particular", "Parcialmente", "Generalmente", "Difícilmente"], "answer": "Especialmente / en particular", "subject": "Inglés"},
    {"question": "I don’t like coffee means:", "options": ["No me gusta el café", "Me gusta el café", "Quiero un café", "No quiero café"], "answer": "No me gusta el café", "subject": "Inglés"},
    {"question": "He can play the guitar means:", "options": ["Él sabe tocar la guitarra / puede tocar la guitarra", "Él no sabe tocar la guitarra", "Él quiere tocar la guitarra", "Él compra una guitarra"], "answer": "Él sabe tocar la guitarra / puede tocar la guitarra", "subject": "Inglés"},
    {"question": "What is the English term for 'unidad de procesamiento central'?", "options": ["CPU (Central Processing Unit)", "RAM", "Hard Drive", "Motherboard"], "answer": "CPU (Central Processing Unit)", "subject": "Inglés"},
    {"question": "How do you translate the technical term 'firewall' into Spanish?", "options": ["Cortafuegos", "Muro de datos", "Copia de seguridad", "Dirección IP"], "answer": "Cortafuegos", "subject": "Inglés"},
    {"question": "To perform a backup means:", "options": ["Hacer una copia de seguridad", "Reiniciar el ordenador", "Formatear el disco duro", "Borrar archivos temporales"], "answer": "Hacer una copia de seguridad", "subject": "Inglés"},
    {"question": "What is the translation of the word 'database'?", "options": ["Base de datos", "Estructura de red", "Controlador de dominio", "Cifrado de archivos"], "answer": "Base de datos", "subject": "Inglés"},
    {"question": "The term 'Operating System' is translated as:", "options": ["Sistema Operativo", "Operador de Sistemas", "Sistema de Red", "Configuración de Servidores"], "answer": "Sistema Operativo", "subject": "Inglés"},
    {"question": "To solve a network issue, you perform 'troubleshooting'. This means:", "options": ["Diagnóstico y resolución de problemas", "Instalación de cables ethernet", "Configuración de contraseñas", "Descarga de actualizaciones"], "answer": "Diagnóstico y resolución de problemas", "subject": "Inglés"},
    {"question": "What is the Spanish equivalent of 'user account'?", "options": ["Cuenta de usuario", "Nombre del servidor", "Grupo de seguridad", "Contraseña de acceso"], "answer": "Cuenta de usuario", "subject": "Inglés"},
    {"question": "In English, the term 'Software License' means:", "options": ["Licencia de software / acuerdo de uso", "Instalación de programas", "Código fuente libre", "Cortafuegos corporativo"], "answer": "Licencia de software / acuerdo de uso", "subject": "Inglés"},
    {"question": "How do you translate the verb 'to decrypt'?", "options": ["Descifrar / desencriptar", "Cifrar", "Borrar", "Comprimir"], "answer": "Descifrar / desencriptar", "subject": "Inglés"},
    {"question": "The English term 'Local Area Network' is abbreviated as:", "options": ["LAN", "WAN", "MAN", "VPN"], "answer": "LAN", "subject": "Inglés"},
    {"question": "To upgrade a system means:", "options": ["Actualizar a una versión superior o mejorada", "Restaurar el sistema a valores de fábrica", "Eliminar programas antiguos", "Hacer copia en cinta"], "answer": "Actualizar a una versión superior o mejorada", "subject": "Inglés"},
    {"question": "What does the expression 'Default Gateway' mean in Spanish?", "options": ["Puerta de enlace predeterminada", "Dirección IP estática", "Máscara de subred", "Servidor DNS principal"], "answer": "Puerta de enlace predeterminada", "subject": "Inglés"},
    {"question": "How is 'Cloud Storage' translated into Spanish?", "options": ["Almacenamiento en la nube", "Memoria RAM del servidor", "Copia en disco duro externo", "Red de área local"], "answer": "Almacenamiento en la nube", "subject": "Inglés"},
    {"question": "What is the meaning of the adjective 'wired' when talking about networks?", "options": ["Cableado / con cables", "Inalámbrico (wireless)", "Cifrado", "Saturado"], "answer": "Cableado / con cables", "subject": "Inglés"},
    {"question": "In IT, 'to install patch' means:", "options": ["Instalar un parche de actualización / seguridad", "Formatear el sistema", "Crear una partición", "Cambiar la tarjeta de red"], "answer": "Instalar un parche de actualización / seguridad", "subject": "Inglés"},
    {"question": "What is the translation of 'wireless connection'?", "options": ["Conexión inalámbrica", "Conexión por cable coaxial", "Red de fibra óptica", "Conexión serie remota"], "answer": "Conexión inalámbrica", "subject": "Inglés"},
    {"question": "To monitor network traffic means:", "options": ["Monitorear / supervisar el tráfico de red", "Bloquear el acceso de usuarios externos", "Aumentar el ancho de banda", "Cambiar los routers de la oficina"], "answer": "Monitorear / supervisar el tráfico de red", "subject": "Inglés"}
]
questions.extend(ing_qs)

# 8. Empleabilidad I (20)
emp1_qs = [
    {"question": "¿Qué característica tiene un buen objetivo de aprendizaje según las metodologías de estudio?", "options": ["Debe ser específico, medible, alcanzable, relevante y con un tiempo definido (SMART)", "Debe ser muy largo y difícil de conseguir", "Debe ser genérico y sin plazos de entrega", "Debe depender de otras personas para lograrlo"], "answer": "Debe ser específico, medible, alcanzable, relevante y con un tiempo definido (SMART)", "subject": "Empleabilidad I"},
    {"question": "¿Qué objetivo principal tienen las medidas de conciliación de la vida laboral y familiar en las leyes laborales?", "options": ["Reducir el salario de los trabajadores", "Permitir compatibilizar el desarrollo profesional con la vida personal y familiar", "Aumentar las horas de la jornada laboral", "Favorecer los despidos disciplinarios"], "answer": "Permitir compatibilizar el desarrollo profesional con la vida personal y familiar", "subject": "Empleabilidad I"},
    {"question": "¿Qué caracteriza a una identidad digital coherente y profesional de un trabajador en la red?", "options": ["Tener perfiles públicos con información contradictoria o poco cuidada", "Mantener una presencia en redes sociales alineada con los valores profesionales y el sector laboral", "No tener ninguna presencia digital en absoluto", "Publicar únicamente opiniones personales controvertidas"], "answer": "Mantener una presencia en redes sociales alineada con los valores profesionales y el sector laboral", "subject": "Empleabilidad I"},
    {"question": "¿Qué norma de rango supremo en España fundamenta los derechos y deberes laborales básicos?", "options": ["La Constitución Española de 1978", "El Estatuto de los Trabajadores", "El Convenio Colectivo de empresa", "El Contrato Laboral individual"], "answer": "La Constitución Española de 1978", "subject": "Empleabilidad I"},
    {"question": "En el Estatuto de los Trabajadores, ¿cuál es el límite de la jornada laboral diaria ordinaria general, salvo pacto en contrario?", "options": ["8 horas diarias", "9 horas diarias", "10 horas diarias", "6 horas diarias"], "answer": "9 horas diarias", "subject": "Empleabilidad I"},
    {"question": "¿Qué tipo de contrato laboral se concierta por tiempo indefinido pero para realizar trabajos estacionales o periódicos de forma discontinua?", "options": ["Contrato fijo-discontinuo", "Contrato a tiempo parcial temporal", "Contrato de sustitución", "Contrato formativo"], "answer": "Contrato fijo-discontinuo", "subject": "Empleabilidad I"},
    {"question": "En una nómina, ¿a qué corresponden los 'devengos'?", "options": ["A los descuentos fiscales y retenciones de la Seguridad Social", "A las cantidades económicas totales que recibe el trabajador en concepto de salario u otros complementos (salario bruto)", "Al dinero líquido neto que se cobra", "A las aportaciones del empresario a Hacienda"], "answer": "A las cantidades económicas totales que recibe el trabajador en concepto de salario u otros complementos (salario bruto)", "subject": "Empleabilidad I"},
    {"question": "¿Qué tipo de despido empresarial se extingue por causas económicas justificadas de la empresa pagando 20 días por año trabajado?", "options": ["Despido por causas objetivas", "Despido disciplinario", "Despido colectivo masivo", "Dimisión forzada"], "answer": "Despido por causas objetivas", "subject": "Empleabilidad I"},
    {"question": "En prevención de riesgos laborales, ¿qué es un riesgo laboral?", "options": ["La posibilidad de que un trabajador sufra un determinado daño derivado del trabajo", "El accidente físico real que ha ocurrido", "La baja médica firmada por el facultativo", "La multa que recibe el empresario por incumplir las medidas"], "answer": "La posibilidad de que un trabajador sufra un determinado daño derivado del trabajo", "subject": "Empleabilidad I"},
    {"question": "¿Cuál de los siguientes es un derecho básico de los trabajadores recogido en el Estatuto de los Trabajadores?", "options": ["Derecho a la libre elección de profesión u oficio", "Derecho a no pagar impuestos sobre el salario", "Derecho a fijar su propio horario de trabajo", "Derecho a vacaciones indefinidas pagadas"], "answer": "Derecho a la libre elección de profesión u oficio", "subject": "Empleabilidad I"},
    {"question": "En el cálculo de una nómina, ¿qué contingencia financia las prestaciones por accidentes de trabajo y enfermedades profesionales?", "options": ["Contingencias Profesionales (AT y EP)", "Contingencias Comunes", "Fondo de Desempleo", "Aportaciones al FOGASA"], "answer": "Contingencias Profesionales (AT y EP)", "subject": "Empleabilidad I"},
    {"question": "¿Qué es la negociación colectiva?", "options": ["El pacto de salario entre un trabajador y su jefe directo", "La negociación entre sindicatos y patronales para acordar las condiciones de trabajo plasmadas en convenios", "La junta general de accionistas de la corporación", "El arbitraje del Ministerio de Trabajo en una huelga"], "answer": "La negociación entre sindicatos y patronales para acordar las condiciones de trabajo plasmadas en convenios", "subject": "Empleabilidad I"},
    {"question": "¿Qué derecho constitucional permite a los trabajadores afiliarse libremente al sindicato de su elección?", "options": ["Derecho a la Libertad Sindical", "Derecho de Asociación general", "Derecho al Trabajo", "Derecho a la Huelga colectiva"], "answer": "Derecho a la Libertad Sindical", "subject": "Empleabilidad I"},
    {"question": "En prevención de riesgos laborales, ¿cuál es el primer paso o prioridad en la jerarquía de medidas preventivas?", "options": ["Eliminar el riesgo en su origen si es posible", "Entregar Equipos de Protección Individual (EPIs)", "Colocar señales de peligro de colores", "Dar charlas formativas a los trabajadores"], "answer": "Eliminar el riesgo en su origen si es posible", "subject": "Empleabilidad I"},
    {"question": "¿Qué tipo de despido se declara en el juzgado de lo social cuando el empresario no consigue demostrar la causa del despido alegada?", "options": ["Despido Improcedente", "Despido Nulo", "Despido Procedente", "Despido Objetivo"], "answer": "Despido Improcedente", "subject": "Empleabilidad I"},
    {"question": "¿Cuál es la indemnización por despido por causas objetivas procedente regulada en España?", "options": ["20 días de salario por año de servicio, prorrateándose por meses los períodos de tiempo inferiores a un año, con un máximo de 12 mensualidades", "33 días por año trabajado con tope de 24 mensualidades", "45 días por año trabajado con tope de 42 mensualidades", "No hay indemnización por despido procedente"], "answer": "20 días de salario por año de servicio, prorrateándose por meses los períodos de tiempo inferiores a un año, con un máximo de 12 mensualidades", "subject": "Empleabilidad I"},
    {"question": "¿Qué es un accidente de trabajo 'in itinere'?", "options": ["Un accidente ocurrido dentro del taller de la empresa", "El que sufre el trabajador al ir o al volver del lugar de trabajo", "Un accidente leve que no requiere baja médica", "El que ocurre durante las horas de descanso pactadas en el Estatuto"], "answer": "El que sufre el trabajador al ir o al volver del lugar de trabajo", "subject": "Empleabilidad I"},
    {"question": "En el régimen general de la Seguridad Social de España, ¿quién asume el mayor porcentaje de cotización de la nómina del trabajador?", "options": ["El empresario", "El propio trabajador", "El Estado mediante subvenciones", "La mutua patronal"], "answer": "El empresario", "subject": "Empleabilidad I"},
    {"question": "En derecho laboral, ¿qué es la condición más beneficiosa?", "options": ["Un principio que mantiene los derechos que los trabajadores hayan adquirido previamente mediante contrato individual si son mejores que los del convenio", "El aumento salarial aprobado por el Gobierno", "El derecho a elegir el mes de vacaciones", "Un acuerdo colectivo nacional de la patronal"], "answer": "Un principio que mantiene los derechos que los trabajadores hayan adquirido previamente mediante contrato individual si son mejores que los del convenio", "subject": "Empleabilidad I"},
    {"question": "¿Qué organismo público tiene como función principal vigilar el cumplimiento de la normativa laboral y de prevención de riesgos imponiendo sanciones?", "options": ["La Inspección de Trabajo y Seguridad Social", "El SEPE", "La Tesorería General de la Seguridad Social", "Los juzgados de lo civil"], "answer": "La Inspección de Trabajo y Seguridad Social", "subject": "Empleabilidad I"}
]
questions.extend(emp1_qs)

# 9. Empleabilidad II (20)
emp2_qs = [
    {"question": "¿Qué diferencia sustancial hay entre creatividad e innovación en el desarrollo empresarial?", "options": ["La creatividad es la generación de ideas nuevas y útiles, mientras que la innovación es la aplicación práctica de esas ideas con éxito comercial", "La creatividad requiere inversión económica y la innovación es gratuita", "No hay ninguna diferencia técnica", "La creatividad solo la tienen los artistas y la innovación los ingenieros"], "answer": "La creatividad es la generación de ideas nuevas y útiles, mientras que la innovación es la aplicación práctica de esas ideas con éxito comercial", "subject": "Empleabilidad II"},
    {"question": "En modelos de negocio, ¿qué describe el término 'difusión de la innovación'?", "options": ["El envío del catálogo por correo electrónico", "La velocidad y el proceso por el cual una nueva idea, producto o tecnología es adoptada por los miembros de un mercado social", "La creación de patentes industriales internacionales", "La publicidad tradicional en televisión"], "answer": "La velocidad y el proceso por el cual una nueva idea, producto o tecnología es adoptada por los miembros de un mercado social", "subject": "Empleabilidad II"},
    {"question": "¿Qué caracteriza principalmente a un proyecto de 'emprendimiento social'?", "options": ["Que no busca obtener ningún tipo de beneficio económico", "Que su objetivo principal es resolver un problema social o medioambiental aplicando herramientas y lógicas empresariales", "Que se financia únicamente mediante donaciones públicas", "Que solo vende productos a través de redes sociales"], "answer": "Que su objetivo principal es resolver un problema social o medioambiental aplicando herramientas y lógicas empresariales", "subject": "Empleabilidad II"},
    {"question": "En el lienzo Canvas, ¿qué bloque representa las alianzas estratégicas con proveedores o socios clave?", "options": ["Asociaciones Clave (Key Partners)", "Relaciones con Clientes", "Recursos Clave", "Canales"], "answer": "Asociaciones Clave (Key Partners)", "subject": "Empleabilidad II"},
    {"question": "¿Qué documento redacta un emprendedor detallando el estudio de mercado, plan de operaciones, marketing y finanzas de su idea de negocio?", "options": ["Plan de Empresa / Plan de Negocio", "Balance de situación", "Cuenta de pérdidas y ganancias", "Acta constitucional"], "answer": "Plan de Empresa / Plan de Negocio", "subject": "Empleabilidad II"},
    {"question": "En el análisis DAFO, ¿qué son las 'Oportunidades'?", "options": ["Factores internos positivos que la empresa puede controlar directamente", "Factores externos del entorno o mercado que la empresa puede aprovechar para crecer", "Las debilidades de los trabajadores de la plantilla", "Los préstamos concedidos por las entidades bancarias"], "answer": "Factores externos del entorno o mercado que la empresa puede aprovechar para crecer", "subject": "Empleabilidad II"},
    {"question": "En marketing mix, ¿qué bloque describe cómo se distribuye y hace llegar el producto al cliente final?", "options": ["Plaza (Place / Distribución)", "Producto (Product)", "Precio (Price)", "Promoción (Promotion)"], "answer": "Plaza (Place / Distribución)", "subject": "Empleabilidad II"},
    {"question": "¿Cuál es la forma jurídica de empresa unipersonal que responde a las deudas del negocio de manera ilimitada con su patrimonio personal?", "options": ["Empresario Individual / Autónomo", "Sociedad Limitada Unipersonal (S.L.U.)", "Sociedad Anónima Unipersonal (S.A.U.)", "Sociedad Cooperativa"], "answer": "Empresario Individual / Autónomo", "subject": "Empleabilidad II"},
    {"question": "En finanzas de proyectos, ¿a qué corresponden los costes fijos de una empresa?", "options": ["A los gastos que permanecen constantes a corto plazo independientemente del volumen de producción (ej. alquiler de oficina)", "A los costes de las materias primas para fabricar el producto", "A los impuestos anuales sobre beneficios comerciales", "Al capital social mínimo aportado por los socios"], "answer": "A los gastos que permanecen constantes a corto plazo independientemente del volumen de producción (ej. alquiler de oficina)", "subject": "Empleabilidad II"},
    {"question": "En el lienzo Canvas, ¿qué bloque describe cómo cobra el negocio y de dónde proceden sus ingresos principales?", "options": ["Fuentes de Ingresos (Revenue Streams)", "Estructura de Costes", "Canales", "Propuesta de Valor"], "answer": "Fuentes de Ingresos (Revenue Streams)", "subject": "Empleabilidad II"},
    {"question": "¿Qué método ágil para startups prioriza validar hipótesis del modelo de negocio en el mercado real con un producto mínimo viable?", "options": ["Lean Startup", "Metodología Waterfall tradicional", "Planificación estratégica rígida", "Modelo de cascada"], "answer": "Lean Startup", "subject": "Empleabilidad II"},
    {"question": "¿Qué es la financiación mediante Crowdfunding?", "options": ["Préstamos concedidos por el Banco Central", "Financiación colectiva en línea donde multitud de personas aportan pequeñas cantidades a un proyecto", "Subvenciones a fondo perdido europeas", "El uso de ahorros personales del emprendedor"], "answer": "Financiación colectiva en línea donde multitud de personas aportan pequeñas cantidades a un proyecto", "subject": "Empleabilidad II"},
    {"question": "En contabilidad, ¿cómo se denominan a los bienes y derechos propiedad de una empresa (como ordenadores, furgonetas, dinero en banco)?", "options": ["Activo", "Pasivo", "Patrimonio Neto", "Pérdidas acumuladas"], "answer": "Activo", "subject": "Empleabilidad II"},
    {"question": "¿Cuál es el capital social mínimo obligatorio para constituir una Sociedad Anónima (S.A.) en España?", "options": ["3.000 euros", "60.000 euros", "120.000 euros", "No hay límite mínimo legal"], "answer": "60.000 euros", "subject": "Empleabilidad II"},
    {"question": "En el análisis DAFO, ¿qué elemento representa una debilidad?", "options": ["El aumento de impuestos en el sector", "La falta de experiencia del equipo fundador del proyecto (factor interno negativo)", "La existencia de competidores fuertes en la zona", "El lanzamiento de una nueva línea de ayudas públicas"], "answer": "La falta de experiencia del equipo fundador del proyecto (factor interno negativo)", "subject": "Empleabilidad II"},
    {"question": "En el diseño de modelos de negocio Canvas, ¿qué representan las 'Actividades Clave'?", "options": ["Los eventos recreativos organizados para los trabajadores", "Las tareas operativas indispensables para poder entregar nuestra propuesta de valor al cliente", "Las acciones de publicidad en redes sociales", "Las reuniones periódicas con los inversores"], "answer": "Las tareas operativas indispensables para poder entregar nuestra propuesta de valor al cliente", "subject": "Empleabilidad II"},
    {"question": "¿Qué tributo indirecto grava el consumo de bienes y servicios y debe ser declarado periódicamente por las empresas?", "options": ["IVA (Impuesto sobre el Valor Añadido)", "Impuesto sobre Sociedades", "IRPF", "IAE"], "answer": "IVA (Impuesto sobre el Valor Añadido)", "subject": "Empleabilidad II"},
    {"question": "En emprendimiento, ¿qué es un Pitch?", "options": ["Un documento financiero muy largo", "Una presentación breve y concisa para vender una idea de negocio a inversores o clientes en pocos minutos", "Un tipo de contrato mercantil de distribución", "El logotipo de una marca corporativa"], "answer": "Una presentación breve y concisa para vender una idea de negocio a inversores o clientes en pocos minutos", "subject": "Empleabilidad II"},
    {"question": "En el plan de empresa, ¿cuál es la función del organigrama?", "options": ["Calcular la factura de la luz mensual", "Representar de forma gráfica la estructura organizativa, jerarquía y departamentos del personal de la empresa", "Describir el proceso de fabricación técnica", "Listar los competidores del sector"], "answer": "Representar de forma gráfica la estructura organizativa, jerarquía y departamentos del personal de la empresa", "subject": "Empleabilidad II"},
    {"question": "En Lean Startup, ¿qué significa el término 'Pivotar'?", "options": ["Cambiar de local comercial de forma física", "Corregir o cambiar el rumbo estratégico de la startup basándose en los resultados reales de validación con clientes", "Despedir a la mitad de la plantilla para reducir costes", "Aumentar los precios del producto estrella"], "answer": "Corregir o cambiar el rumbo estratégico de la startup basándose en los resultados reales de validación con clientes", "subject": "Empleabilidad II"}
]
questions.extend(emp2_qs)

# Generate JS array code
js_array_lines = []
js_array_lines.append("const SEED_REPASO_QUESTIONS = [")
for idx, q in enumerate(questions):
    js_array_lines.append("    {")
    js_array_lines.append(f'        question: {json.dumps(q["question"], ensure_ascii=False)},')
    
    # Options formatting
    opts_str = ", ".join(json.dumps(opt, ensure_ascii=False) for opt in q["options"])
    js_array_lines.append(f'        options: [{opts_str}],')
    
    js_array_lines.append(f'        answer: {json.dumps(q["answer"], ensure_ascii=False)},')
    js_array_lines.append(f'        subject: {json.dumps(q["subject"], ensure_ascii=False)},')
    js_array_lines.append(f'        source: "repaso"')
    
    if idx < len(questions) - 1:
        js_array_lines.append("    },")
    else:
        js_array_lines.append("    }")
js_array_lines.append("];")

js_array_code = "\n".join(js_array_lines)

def main():
    print(f"Generated {len(questions)} high-quality Cesur-based questions.")
    # Read app.js
    with open("app.js", "r", encoding="utf-8") as f:
        content = f.read()

    # Replace SEED_REPASO_QUESTIONS pattern in app.js
    # The array begins with "const SEED_REPASO_QUESTIONS = [" and ends before "// STATE AND DATABASE MANAGEMENT"
    pattern = r"const SEED_REPASO_QUESTIONS = \[.*?\];\n"
    match = re.search(pattern, content, re.DOTALL)
    if match:
        new_content = content.replace(match.group(0), js_array_code + "\n")
        with open("app.js", "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated app.js with 180 high-quality questions!")
    else:
        print("Could not find SEED_REPASO_QUESTIONS pattern in app.js")

if __name__ == "__main__":
    main()
